# Generated by Django 4.2.6 on 2023-10-19 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('situacao', models.CharField(max_length=20)),
                ('bandeira', models.CharField(max_length=20)),
                ('numero', models.CharField(max_length=30)),
                ('cvv', models.CharField(max_length=5)),
                ('validade', models.DateField()),
            ],
            options={
                'verbose_name': 'Cartao',
                'verbose_name_plural': 'Cartões',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=10)),
                ('foto_logo', models.CharField(max_length=100)),
                ('senha', models.IntegerField()),
                ('data_nascimento', models.DateField()),
                ('data_abertura', models.DateField()),
                ('nome_razaoSocial', models.CharField(max_length=100)),
                ('nomeSocial_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('inscricao_estadual', models.CharField(max_length=100)),
                ('inscricao_municipal', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=15)),
                ('cpf', models.CharField(max_length=15)),
                ('cliente_tipo', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'CLientes',
            },
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('agencia', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=20)),
                ('limite', models.IntegerField()),
                ('tipo', models.CharField(max_length=100)),
                ('ativa', models.BooleanField()),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('juros', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numero_parcela', models.IntegerField()),
                ('data_solicitacao', models.DateField()),
                ('data_aprovacao', models.DateField()),
                ('aprovado', models.BooleanField()),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('observacao', models.CharField(max_length=200)),
                ('fk_codigo_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
        migrations.CreateModel(
            name='Movitencao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('operacao', models.CharField(max_length=1)),
                ('data_Hora', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fk_codigo_cartao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cartao')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('grauRisco', models.CharField(max_length=5)),
                ('finalizado', models.BooleanField()),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('aporte', models.DecimalField(decimal_places=2, max_digits=20)),
                ('tipo', models.CharField(max_length=30)),
                ('prazo', models.CharField(max_length=20)),
                ('taxa_administracao', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fk_codigo_conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('bairro', models.CharField(max_length=100)),
                ('logradouro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('fk_codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Endereco',
                'verbose_name_plural': 'Enderecos',
            },
        ),
        migrations.CreateModel(
            name='EmpretimoParcela',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=20)),
                ('numero', models.IntegerField()),
                ('data_pagamento', models.DateField()),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fk_codigo_emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.emprestimo')),
            ],
            options={
                'verbose_name': 'Parcela',
                'verbose_name_plural': 'Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('observacao', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('ramal', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=15)),
                ('fk_codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
        migrations.AddField(
            model_name='cartao',
            name='fk_codigo_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.conta'),
        ),
    ]
