# Generated by Django 4.2.6 on 2023-11-14 11:53

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, max_length=10, null=True)),
                ('senha', models.IntegerField(blank=True, null=True)),
                ('data_abertura', models.DateField(auto_now_add=True, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=15, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('numero', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('saldo', models.FloatField(blank=True, null=True)),
                ('emprestimo', models.FloatField(blank=True, default=0)),
                ('cartao', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.upload_image)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('data_Hora', models.DateTimeField(auto_now=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cliente_pagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_cliente_pagar', to='core.cliente')),
                ('cliente_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacao_cliente_receber', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Movimentação',
                'verbose_name_plural': 'Movimentações',
            },
        ),
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('grauRisco', models.CharField(max_length=5)),
                ('rentabilidade', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Codigo_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('valor_solicitado', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Codigo_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprestimo_cliente', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Emprestimo',
                'verbose_name_plural': 'Emprestimos',
            },
        ),
    ]
