# Generated by Django 4.2.6 on 2023-10-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmpretimoParcela',
            new_name='EmprestimoParcela',
        ),
        migrations.RenameModel(
            old_name='Movitencao',
            new_name='Movimentacao',
        ),
        migrations.RenameField(
            model_name='conta',
            old_name='codigo_cliente',
            new_name='fk_codigo_cliente',
        ),
    ]
